#INCLUDE <p16f628a.inc>

__CONFIG _BODEN_ON & _CP_OFF & _PWRTE_ON & _WDT_OFF & _LVP_OFF & _MCLRE_ON & _XT_OSC

#DEFINE BANK0 BCF STATUS,RP0 ;SETA BANK 0 DE MEMÓRIA
#DEFINE BANK1 BSF STATUS,RP0 ;SETA BANK 1 DE MAMÓRIA


ORG 0x00 ;ENDEREÇO INICIAL DE PROCESSAMENTO
GOTO INICIO


ORG 0x04 ;ENDEREÇO INICIAL DA INTERRUPÇÃO
RETFIE ;RETORNA DA INTERRUPÇÃO


INICIO
BANK0 ;ALTERA PARA O BANCO 0
MOVLW B'00000111'
MOVWF CMCON ;DEFINE O MODO DE OPERAÇÃO DO COMPARADOR ANALÓGICO

CLRF PORTA ;LIMPA O PORTA
CLRF PORTB ;LIMPA O PORTB

BANK1 ;ALTERA PARA O BANCO 1
MOVLW B'11111110'
MOVWF TRISA ;DEFINE RA2 COMO ENTRADA E DEMAIS
;COMO SAÍDAS
MOVLW B'00000000'
MOVWF TRISB ;DEFINE TODO O PORTB COMO SAÍDA
MOVLW B'10000000'
MOVWF OPTION_REG ;PULL-UPS DESABILITADOS
;AS DEMAIS CONFG. SÃO IRRELEVANTES

MOVLW B'00000000'
MOVWF INTCON ;TODAS AS INTERRUPÇÕES DESLIGADAS
BANK0 ;RETORNA PARA O BANCO 0

MAIN

BTFSC PORTA, 1
GOTO BOTAO_LIB ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
GOTO BOTAO_PRES ;SIM, ENTÃO TRATA BOTÃO PRESSIONADO


BOTAO_LIB

movlw b'00001111'
movwf PORTB
clrf PORTA
GOTO MAIN


BOTAO_PRES

movlw b'11110000'
movwf PORTB
movlw b'00000001'
movwf PORTA
GOTO MAIN ;RETORNA AO LOOP PRINCIPAL



END