#INCLUDE <p16f628a.inc>

__CONFIG _BODEN_ON & _CP_OFF & _PWRTE_ON & _WDT_OFF & _LVP_OFF & _MCLRE_OFF & _XT_OSC

#DEFINE BANK0 BCF STATUS,RP0 ;SETA BANK 0 DE MEMÓRIA
#DEFINE BANK1 BSF STATUS,RP0 ;SETA BANK 1 DE MAMÓRIA


ORG 0x00 ;ENDEREÇO INICIAL DE PROCESSAMENTO
GOTO INICIO


ORG 0x04 ;ENDEREÇO INICIAL DA INTERRUPÇÃO
RETFIE ;RETORNA DA INTERRUPÇÃO

CBLOCK	0x20		;ENDEREÇO INICIAL DA MEMÓRIA DE

	TEMP1                   
	TEMP2
	PA_TEMP		    
	W_TEMP		
	STATUS_TEMP	
	MOTOR

ENDC
    
	
INICIO

BANK0 ;ALTERA PARA O BANCO 0
MOVLW B'00000111'
MOVWF CMCON ;DEFINE O MODO DE OPERAÇÃO DO COMPARADOR ANALÓGICO

CLRF PORTA ;LIMPA O PORTA
CLRF PORTB ;LIMPA O PORTB

BANK1 ;ALTERA PARA O BANCO 1
MOVLW B'11111110'
MOVWF TRISA ;DEFINE RA2 COMO ENTRADA E DEMAIS COMO SAÍDAS
	
MOVLW B'00000000'
MOVWF TRISB ;DEFINE TODO O PORTB COMO SAÍDA
	
MOVLW B'10000000'
MOVWF OPTION_REG ;PULL-UPS DESABILITADOS
;AS DEMAIS CONFG. SÃO IRRELEVANTES

MOVLW B'00000000'
MOVWF INTCON ;TODAS AS INTERRUPÇÕES DESLIGADAS
BANK0 ;RETORNA PARA O BANCO 0
	
	
MAIN

CALL SERVO90	
	
BTFSC PORTA, 1
GOTO BOTAO_LIB ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
GOTO VERIFICA ;SIM, ENTÃO TRATA BOTÃO PRESSIONADO

BOTAO_LIB
    BTFSC PORTA, 2
    GOTO BOTAO_LIB2 ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
    GOTO VELOCIDADE2 ;SIM, ENTÃO TRATA BOTÃO PRESSIONADO
    
BOTAO_LIB2
    BTFSC PORTA, 4
    GOTO BOTAO_LIB3 ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
    GOTO VELOCIDADE1A ;SIM, ENTÃO TRATA BOTÃO PRESSIONADO    

BOTAO_LIB3
    BTFSC PORTA, 5
    GOTO MAIN ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
    GOTO VELOCIDADE2A ;SIM, ENTÃO TRATA BOTÃO PRESSIONADO    
    
VERIFICA
    
    BTFSC PORTA, 2
    GOTO VERIFICA2 ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
    GOTO VELOCIDADE2A ;SIM, ENTÃO TRATA BOTÃO PRESSIONADO
    
VERIFICA2
    
    BTFSC PORTA, 3
    GOTO VELOCIDADE1 ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
    GOTO SERVO180 ;SIM, ENTÃO TRATA BOTÃO PRESSIONADO    
    
VELOCIDADE1	
    
    CALL SERVO0
    
    BCF	PORTB,0	
    BSF	PORTB,3
    BSF	PORTB,2 	

    CALL DELAY100ms

    BCF	PORTB,3
    BSF	PORTB,1	

    CALL DELAY100ms	

    BCF	PORTB,2	
    BSF	PORTB,0	

    CALL DELAY100ms		

    BCF	PORTB,1
    BSF	PORTB,3	

    CALL DELAY100ms
    
BTFSC PORTA,3
GOTO VELOCIDADE1 ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
GOTO MAIN ;SIM, ENTÃO TRATA BOTÃO PRESSIONADO

 
 VELOCIDADE2	
	
    CALL SERVO45
 
    BCF	PORTB,0	
    BSF	PORTB,3
    BSF	PORTB,2 	

    CALL DELAY10ms

    BCF	PORTB,3
    BSF	PORTB,1	

    CALL DELAY10ms	

    BCF	PORTB,2	
    BSF	PORTB,0	

    CALL DELAY10ms		

    BCF	PORTB,1
    BSF	PORTB,3	

    CALL DELAY10ms
    
BTFSC PORTA,3
GOTO VELOCIDADE2 ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
GOTO MAIN ;SIM, ENTÃO TRATA BOTÃO PRESSIONADO

;-----------------------------------------------------------------------    
    
VELOCIDADE1A	
	
    CALL SERVO135
    
    BCF	PORTB,3		
    BSF	PORTB,0
    BSF	PORTB,1 	

    CALL DELAY100ms

    BCF	PORTB,0	
    BSF	PORTB,2	

    CALL DELAY100ms	

    BCF	PORTB,1	
    BSF	PORTB,3	

    CALL DELAY100ms		

    BCF	PORTB,2
    BSF	PORTB,0	

    CALL DELAY100ms
    
BTFSC PORTA,3
GOTO VELOCIDADE1A ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
GOTO MAIN ;SIM, ENTÃO TRATA BOTÃO PRESSIONADO

 
VELOCIDADE2A	
    
    CALL SERVO180
	
    BCF	PORTB,3		
    BSF	PORTB,0
    BSF	PORTB,1 	

    CALL DELAY10ms

    BCF	PORTB,0	
    BSF	PORTB,2	

    CALL DELAY10ms	

    BCF	PORTB,1	
    BSF	PORTB,3	

    CALL DELAY10ms		

    BCF	PORTB,2
    BSF	PORTB,0	

    CALL DELAY10ms
    
BTFSC PORTA,3
GOTO VELOCIDADE2A ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
GOTO MAIN ;SIM, ENTÃO TRATA BOTÃO PRESSIONADO
    


    
DELAY20ms ; OK

	MOVLW .100	    ; PASSA VALOR PARA ACUMULADOR
	MOVWF TEMP1	    ; PASSA VALOR ACUMULADOR PARA REGISTRADOR 1
	
DL1A4
	MOVLW .19	    ; PASSA VALOR PARA ACUMULADOR
	MOVWF TEMP2	    ; PASSA VALOR ACUMULADOR PARA REGISTRADOR 2

	DECFSZ TEMP1, F	    ; 1 CICLO DE MAQUINA   - DECREMENTA REGISTRADOR
	GOTO DL2A4
	RETURN	
	
DL2A4
	NOP		    ; 1 CICLO DE MAQUINA   |  = 5 Ciclos
	NOP		    ; 1 CICLO DE MAQUINA   |
	DECFSZ TEMP2, F	    ; 1 CICLO DE MAQUINA   - DECREMENTA REGISTRADOR
	GOTO DL2A4	    ; 2 CICLO DE MAQUINA
	GOTO DL1A4
	
	;TEMPO = 5 (CICLOS DE MAQUINA)* 100 (QUANTIDADE DO REGISTRADOR)
	;100(TEMP2) * 5(CICLOS) * 2(CICLOS DL1B)* 100(TEMP1
	RETURN	  
	
;------------------------------------------------------------------------------    
    
    
    DELAY10ms ; OK

	MOVLW .100	    ; PASSA VALOR PARA ACUMULADOR
	MOVWF TEMP1	    ; PASSA VALOR ACUMULADOR PARA REGISTRADOR 1
	
DL1A
	MOVLW .10	    ; PASSA VALOR PARA ACUMULADOR
	MOVWF TEMP2	    ; PASSA VALOR ACUMULADOR PARA REGISTRADOR 2

	DECFSZ TEMP1, F	    ; 1 CICLO DE MAQUINA   - DECREMENTA REGISTRADOR
	GOTO DL2A
	RETURN	
	
DL2A
	NOP		    ; 1 CICLO DE MAQUINA   |  = 5 Ciclos
	NOP		    ; 1 CICLO DE MAQUINA   |
	DECFSZ TEMP2, F	    ; 1 CICLO DE MAQUINA   - DECREMENTA REGISTRADOR
	GOTO DL2A	    ; 2 CICLO DE MAQUINA
	GOTO DL1A
	
	;TEMPO = 5 (CICLOS DE MAQUINA)* 100 (QUANTIDADE DO REGISTRADOR)
	;100(TEMP2) * 5(CICLOS) * 2(CICLOS DL1B)* 100(TEMP1
	RETURN	  
	
;------------------------------------------------------------------------------
	
DELAY100ms ; OK

	MOVLW .100	    ; PASSA VALOR PARA ACUMULADOR
	MOVWF TEMP1	    ; PASSA VALOR ACUMULADOR PARA REGISTRADOR 1
	
DL1A1
	MOVLW .100	    ; PASSA VALOR PARA ACUMULADOR
	MOVWF TEMP2	    ; PASSA VALOR ACUMULADOR PARA REGISTRADOR 2

	DECFSZ TEMP1, F	    ; 1 CICLO DE MAQUINA   - DECREMENTA REGISTRADOR
	GOTO DL2A1
	RETURN	
	
DL2A1
	NOP		    ; 1 CICLO DE MAQUINA   |  = 5 Ciclos
	NOP		    ; 1 CICLO DE MAQUINA   |
	DECFSZ TEMP2, F	    ; 1 CICLO DE MAQUINA   - DECREMENTA REGISTRADOR
	GOTO DL2A1	    ; 2 CICLO DE MAQUINA
	GOTO DL1A1
	
	;TEMPO = 5 (CICLOS DE MAQUINA)* 100 (QUANTIDADE DO REGISTRADOR)
	;100(TEMP2) * 5(CICLOS) * 2(CICLOS DL1B)* 100(TEMP1
	RETURN

;------------------------------------------------------------------------------
	
DELAY1ms  ;

	MOVLW .250	    ; PASSA VALOR PARA ACUMULADOR
	MOVWF TEMP1	    ; PASSA VALOR ACUMULADOR PARA REGISTRADOR

DL1

	NOP		    ; 1 CICLO DE MAQUINA
	DECFSZ TEMP1, F	    ; 1 CICLO DE MAQUINA   - DECREMENTA REGISTRADOR
	GOTO DL1	    ; 2 CICLO DE MAQUINA
	
	;TEMPO = 4 (CICLOS DE MAQUINA) * 250(QUANTIDADE DO REGISTRADOR)
	;250 * 4 = 1000us = 1ms
	
	RETURN	
	
;------------------------------------------------------------------------------	

DELAY500us

	MOVLW .125
	MOVWF TEMP1

DL0

	NOP
	DECFSZ TEMP1, F
	GOTO DL0

	RETURN

;------------------------------------------------------------------------------		
	
DELAY250us

	MOVLW .63
	MOVWF TEMP1

DL0W

	NOP
	DECFSZ TEMP1, F
	GOTO DL0W

	RETURN

;------------------------------------------------------------------------------	

SERVO0
	
	BSF PORTB,4
	CALL DELAY1ms
	;CALL DELAY1ms ;Tempo para posição 90º
	BCF PORTB,4
	CALL DELAY20ms

	RETURN

SERVO45
	
	BSF PORTB,4
	CALL DELAY1ms
	CALL DELAY250us
	;CALL DELAY1ms ;Tempo para posição 90º
	BCF PORTB,4
	CALL DELAY20ms

	RETURN	
	
SERVO90
	
	BSF PORTB,4
	CALL DELAY1ms
	CALL DELAY500us
	;CALL DELAY1ms ;Tempo para posição 90º
	BCF PORTB,4
	CALL DELAY20ms

	RETURN

SERVO135
	
	BSF PORTB,4
	CALL DELAY1ms
	CALL DELAY500us
	CALL DELAY250us
	;CALL DELAY1ms ;Tempo para posição 90º
	BCF PORTB,4
	CALL DELAY20ms

	RETURN	
	
SERVO180
	
	BSF PORTB,4
	CALL DELAY1ms
	CALL DELAY1ms
	;CALL DELAY1ms ;Tempo para posição 90º
	BCF PORTB,4
	CALL DELAY20ms

	RETURN	
	
END
    
