#INCLUDE <p16f628a.inc>

__CONFIG _BODEN_ON & _CP_OFF & _PWRTE_ON & _WDT_OFF & _LVP_OFF & _MCLRE_ON & _XT_OSC

#DEFINE BANK0 BCF STATUS,RP0 ;SETA BANK 0 DE MEMÓRIA
#DEFINE BANK1 BSF STATUS,RP0 ;SETA BANK 1 DE MAMÓRIA


ORG 0x00 ;ENDEREÇO INICIAL DE PROCESSAMENTO
GOTO INICIO


ORG 0x04 ;ENDEREÇO INICIAL DA INTERRUPÇÃO
RETFIE ;RETORNA DA INTERRUPÇÃO

CBLOCK	0x20		;ENDEREÇO INICIAL DA MEMÓRIA DE

	TEMP1                   
	TEMP2
	PA_TEMP		    
	W_TEMP		
	STATUS_TEMP	

ENDC
    
	
INICIO

BANK0 ;ALTERA PARA O BANCO 0
MOVLW B'00000111'
MOVWF CMCON ;DEFINE O MODO DE OPERAÇÃO DO COMPARADOR ANALÓGICO

CLRF PORTA ;LIMPA O PORTA
CLRF PORTB ;LIMPA O PORTB

BANK1 ;ALTERA PARA O BANCO 1
MOVLW B'11111110'
MOVWF TRISA ;DEFINE RA2 COMO ENTRADA E DEMAIS
;COMO SAÍDAS
MOVLW B'00000000'
MOVWF TRISB ;DEFINE TODO O PORTB COMO SAÍDA
MOVLW B'10000000'
MOVWF OPTION_REG ;PULL-UPS DESABILITADOS
;AS DEMAIS CONFG. SÃO IRRELEVANTES

MOVLW B'00000000'
MOVWF INTCON ;TODAS AS INTERRUPÇÕES DESLIGADAS
BANK0 ;RETORNA PARA O BANCO 0
	
MAIN
	
BTFSC PORTA, 1
GOTO BOTAO_LIB ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
GOTO BOTAO_PRES ;SIM, ENTÃO TRATA BOTÃO PRESSIONADO

BOTAO_LIB

movlw b'00001111'
movwf PORTB
clrf PORTA
GOTO MAIN

BOTAO_PRES

movlw b'11110000'
movwf PORTB
movlw b'00000001'
movwf PORTA
CALL DELAY500us
GOTO MAIN ;RETORNA AO LOOP PRINCIPAL
	
	
DELAY500us

	MOVLW .125
	MOVWF TEMP1

DL0

	NOP
	DECFSZ TEMP1, F
	GOTO DL0

	RETURN

;------------------------------------------------------------------------------
	
DELAY1ms  ;

	MOVLW .250	    ; PASSA VALOR PARA ACUMULADOR
	MOVWF TEMP1	    ; PASSA VALOR ACUMULADOR PARA REGISTRADOR

DL1

	NOP		    ; 1 CICLO DE MAQUINA
	DECFSZ TEMP1, F	    ; 1 CICLO DE MAQUINA   - DECREMENTA REGISTRADOR
	GOTO DL1	    ; 2 CICLO DE MAQUINA
	
	;TEMPO = 4 (CICLOS DE MAQUINA) * 250(QUANTIDADE DO REGISTRADOR)
	;250 * 4 = 1000us = 1ms
	
	RETURN		  

;------------------------------------------------------------------------------
	
DELAY100ms ; OK

	MOVLW .100	    ; PASSA VALOR PARA ACUMULADOR
	MOVWF TEMP1	    ; PASSA VALOR ACUMULADOR PARA REGISTRADOR 1
	
DL1A
	MOVLW .100	    ; PASSA VALOR PARA ACUMULADOR
	MOVWF TEMP2	    ; PASSA VALOR ACUMULADOR PARA REGISTRADOR 2

	DECFSZ TEMP1, F	    ; 1 CICLO DE MAQUINA   - DECREMENTA REGISTRADOR
	GOTO DL2A
	RETURN	
	
DL2A
	NOP		    ; 1 CICLO DE MAQUINA   |  = 5 Ciclos
	NOP		    ; 1 CICLO DE MAQUINA   |
	DECFSZ TEMP2, F	    ; 1 CICLO DE MAQUINA   - DECREMENTA REGISTRADOR
	GOTO DL2A	    ; 2 CICLO DE MAQUINA
	GOTO DL1A
	
	;TEMPO = 10 (CICLOS DE MAQUINA)* 100 (QUANTIDADE DO REGISTRADOR)
	;1000 * 100 = 100.000us = 100ms
	RETURN

;------------------------------------------------------------------------------

DELAY300ms ; OK

	MOVLW .250	    ; PASSA VALOR PARA ACUMULADOR
	MOVWF TEMP1	    ; PASSA VALOR ACUMULADOR PARA REGISTRADOR 1
	MOVLW .120	    ; PASSA VALOR PARA ACUMULADOR
	MOVWF TEMP2	    ; PASSA VALOR ACUMULADOR PARA REGISTRADOR 2

DL1B
	DECFSZ TEMP1, F	    ; 1 CICLO DE MAQUINA   - DECREMENTA REGISTRADOR
	GOTO DL2B
	RETURN	
	
DL2B
	NOP		    ; 1 CICLO DE MAQUINA   |  = 5 Ciclos
	NOP		    ; 1 CICLO DE MAQUINA   |
	DECFSZ TEMP2, F	    ; 1 CICLO DE MAQUINA   - DECREMENTA REGISTRADOR
	GOTO DL2B	    ; 2 CICLO DE MAQUINA
	GOTO DL1B
	
	;TEMPO = 10 (CICLOS DE MAQUINA) 250 ()QUANTIDADE DO REGISTRADOR
	;2500 * 250 = 625000US = 625MS
	RETURN	

END
    
DELAY10ms ; OK

	MOVLW .100	    ; PASSA VALOR PARA ACUMULADOR
	MOVWF TEMP1	    ; PASSA VALOR ACUMULADOR PARA REGISTRADOR 1
	
DL10
	MOVLW .10	    ; PASSA VALOR PARA ACUMULADOR
	MOVWF TEMP2	    ; PASSA VALOR ACUMULADOR PARA REGISTRADOR 2

	DECFSZ TEMP1, F	    ; 1 CICLO DE MAQUINA   - DECREMENTA REGISTRADOR
	GOTO DL10A
	RETURN	
	
DL10A
	NOP		    ; 1 CICLO DE MAQUINA   |  = 5 Ciclos
	NOP		    ; 1 CICLO DE MAQUINA   |
	DECFSZ TEMP2, F	    ; 1 CICLO DE MAQUINA   - DECREMENTA REGISTRADOR
	GOTO DL10A	    ; 2 CICLO DE MAQUINA
	GOTO DL10
	
	;TEMPO = 5 (CICLOS DE MAQUINA)* 100 (QUANTIDADE DO REGISTRADOR)
	;100(TEMP2) * 5(CICLOS) * 2(CICLOS DL1B)* 100(TEMP1
	RETURN	    
    
